### ISSUE TITLE
MSM Compatibility

### ISSUE THREAD

**Issue by siebird** [bjornbjorn/seo_lite_publisher.ee_addon#2]
Hey Bjørn,

I'm having issues getting the template tags to rendering the meta information on secondary sites with MSM. Initially I thought it was the way I was using the tag:  `last_segment` outside the entries tag vs `entry_id` inside the entries tag. I took a look at the database also to see if the data was writing to the correct `exp_publisher_seolite_content` table and it is. Do you know if this is a bug?

**Comment by bjornbjorn** [comment]
Hi,

can you have a look and see if the "site_id" value is being populated correctly?

**Comment by siebird** [comment]
Yep, it is: http://d.pr/i/195fL

**Comment by bjornbjorn** [comment]
Ok, good ... also, make sure you have visited SEO Lite settings on the secondary site and saved a version of the SEO Lite template to be used on that site.

And, just to clarify, you write:

> Initially I thought it was the way I was using the tag: last_segment outside the entries tag vs entry_id inside the entries tag.

Does that mean it works when using entry_id?

**Comment by siebird** [comment]
Ahh, saving the settings on the second site fixed it! Didn't even realize I needed to do that.

**Comment by bjornbjorn** [comment]
Excellent, thanks for confirming. I know it is a bit unintuitive, this is a general issue with SEO Lite and MSM, haven't gotten around to fixing it yet.
